### PR TITLE
nishant

### PR DESCRIPTION
**Pull request by nishant-madara**
created a new pr @anshumanv

### CODE REVIEW

**Comment by Monal5031** [comment]
Madara Uchiha?

**Comment by nishant-madara** [comment]
yes im madara uchiha

**Comment by rossoskull** [comment]
You can improve the title and description 😄  Btw, Katon: Gouka Mekyakku 🔥  😉

**Comment by anshumanv** [comment]
> yes im madara uchiha

Lolol, I'm Hashirama Senju then 😏

**Comment by nishant-madara** [comment]
"forgive me sasuke there wont be next a next time "

**Comment by nishant-madara** [comment]
........Senpo Mokuton ; Shin Susenju

**Pull request closed without merging**
